### ISSUE TITLE
Consider develop -> master workflow as it relates to Singularity

### ISSUE THREAD

**Issue by bbarker** [federatedcloud/NixTemplates#13]
Even though we are doing dev work in 'develop', if we merger in commits to 'master', a singularity image will be built for each commit in 'master', [with some intelligent caveats](https://github.com/singularityhub/singularityhub.github.io/wiki/Build-A-Container):

> If a user has a repeat tag, then the file with more recent changes (timestamp) is built. Only Singularity files that have been changed since the last commit will be built with Automatic Building in this fashion. If you want to go back int time to a particular commit, you should use a Manual Build. This means that if your push to Github has 10 changed Singularity recipe files, all 10 will be added to the queue to build, and your collection is allowed one active build at a time.

This is probably reasonable, but we should discuss.

**Comment by sk8forether** [comment]
Perhaps it's time we consider separating the Singularity and Docker template repositories?  I think they initially made sense to be together when we thought there was more overlap, but as things have developed, they seem to be diverging.  The Singularity constraints made developing for Docker more complicated, in my opinion, so perhaps a separate Docker repo would ease the difficulties.

**Comment by bbarker** [comment]
@sk8forether maybe, but this is a separate issue from the above, which just pertains to singularity with or without docker.

**Comment by bbarker** [comment]
After discussing with @sk8forether, I realized that there may be some ambiguity in the singularity docs,  so let's just see what happens first after we do a big merge from develop into master.  Specifically, it doesn't make sense that we would kick off multiple builds if only the last one is eventually hosted (I don't think singularity will keep all the builds based on what I read elsewhere).

**Comment by bbarker** [comment]
I've been testing out just merging multiple commits from develop into master (non-squashed!, just regular merge via github PR). It seems to work fine on singularity hub, barring a random and rare github outage (in which case you may have to temporarily switch to manual build under collection settings).
